theme: dinky
title: [LTER Information Managers's Manual]
description: [A getting started guide for serving as the information manager of a Long Term Ecological Research (LTER) Network site]
date: "`r format(Sys.time(), '%d %B, %Y')`"
