theme: jekyll-rtd-theme
title: [LTER Information Managers's Manual]
description: [A getting started guide for serving as the information manager of a Long Term Ecological Research (LTER) Network site]
