remote_theme: pages-themes/dinky@v0.2.0
title: [LTER Information Manager's Manual]
description: [A getting started guide for serving as the information manager of a Long Term Ecological Research (LTER) Network site]
date: "`r format(Sys.time(), '%d %B, %Y')`"
